Repository 6-SSGSAKK/ssgsakk-fe, pull requests merged in 2024-03, with the labels that each got.

#17 Feature/home
  next.config.mjs
  public/images/etc/closeIcon.png
  src/app/(main)/layout.tsx
  src/app/(main)/page.tsx
  src/app/(product)/category/page.tsx
  src/app/layout.tsx
  src/components/UI/FloatingLeft.tsx
  src/components/UI/FloatingUp.tsx
  src/components/UI/HeartIcon.tsx
  src/components/UI/WhiteSpace.tsx
  src/components/common/Modal.tsx
  src/components/images/Cart.tsx
  src/components/images/Heart.tsx
  src/components/images/RedHeart.tsx
  src/components/pages/home/HomeAdCarousel.tsx
  src/components/pages/home/HomeExtraUI.tsx
  src/components/pages/productList/EventProductList.tsx
  tailwind.config.ts
Labels: 🌗Frontend, 💫 feat, 🎨 UI

#27 Dev
  .env
  next.config.mjs
  package.json
  public/images/login/google.png
  src/app/(auth)/join/form/page.tsx
  src/app/(auth)/signup/auth/page.tsx
  src/app/(auth)/signup/intro/page.tsx
  src/app/(auth)/signup/page.tsx
  src/app/(product)/productList/searchProductList/page.tsx
  src/app/globals.css
  src/components/UI/SliderModal.tsx
  src/components/common/SliderModal.tsx
  src/components/common/SliderModalHeader.tsx
  src/components/common/SnsButton.tsx
  src/components/forms/SearchFrom.tsx
  src/components/forms/SearchPage.tsx
  src/components/images/Cart.tsx
  src/components/images/Close.tsx
  src/components/images/DeleteInput.tsx
  src/components/images/ModalSlider.tsx
  src/components/layouts/TopHeader.tsx
  src/components/pages/home/HomeGridItems.tsx
  src/components/pages/join/auth/AuthCard.tsx
  src/components/pages/join/auth/EmailAuthPage.tsx
  src/components/pages/join/auth/ThermList.tsx
  src/components/pages/join/form/JoinAgreeList.tsx
  src/components/pages/join/form/JoinForm.tsx
  src/components/pages/productList/SpecialPriceNavigation.tsx
  src/components/pages/signup/auth/AuthCard.tsx
  src/components/pages/signup/auth/AuthPage.tsx
  src/components/pages/signup/auth/BeforeSignupAgreement.tsx
  src/components/pages/signup/auth/EmailAuthPage.tsx
  src/components/pages/signup/auth/PhoneAgreementList.tsx
  src/components/pages/signup/auth/PhoneAuthPage.tsx
  src/components/pages/signup/auth/ThermList.tsx
  src/components/pages/signup/form/ErrorMessage.tsx
  src/components/pages/signup/form/FormInput.tsx
  src/components/pages/signup/form/FormLabel.tsx
  src/components/pages/signup/form/MarketingAgreeList.tsx
  src/components/pages/signup/form/SearchZipcode.tsx
  src/components/pages/signup/form/SignupForm.tsx
  src/components/pages/signup/form/TextField.tsx
  src/components/pages/signup/intro/JoinIntroCard.tsx
  src/components/pages/signup/intro/SimpleJoinList.tsx
  src/libs/agreementData.tsx
  src/libs/errorMessage.tsx
  src/libs/footerNavigationData.tsx
  src/libs/homeGridItemsData.tsx
  src/libs/homeShoppingmallSelectModalData.tsx
  src/libs/loginDatas.tsx
  src/types/agreementType.tsx
  src/types/homeResourceType.tsx
  src/utils/regex.tsx
  src/utils/timeFormatter.tsx
  tailwind.config.ts
Labels: 🐛 bug, 🌗Frontend, ⚙️ chore, 💫 feat, ♻️ refactor, ✅ test, 🎨 UI

#28 Refactor: global css darkmode delete
  src/app/globals.css
Labels: 🎨 UI

#29 Feature/login
  src/components/common/SnsButton.tsx
Labels: ⚙️ chore, ✅ test
