Repository 6-SSGSAKK/ssgsakk-fe, pull requests merged in 2024-04, with the labels that each got.

#47 Feature/like
  src/actions/useGetClientToken.tsx
  src/actions/useGetServerToken.tsx
  src/app/(member)/layout.tsx
  src/app/(member)/mypage/like/page.tsx
  src/app/(member)/mypage/page.tsx
  src/app/(member)/mypage/shippingList/page.tsx
  src/app/globals.css
  src/components/UI/HeartIcon.tsx
  src/components/common/SliderModal.tsx
  src/components/common/SliderModalHeader.tsx
  src/components/images/FilledHeart.tsx
  src/components/layouts/BottomActionButtons.tsx
  src/components/layouts/TopHeader.tsx
  src/components/pages/category/CategoryHeader.tsx
  src/components/pages/mypage/like/LikeFolder.tsx
  src/components/pages/mypage/like/LikeFolderAdd.tsx
  src/components/pages/mypage/like/LikeFolderManager.tsx
  src/components/pages/mypage/like/LikeHeader.tsx
  src/components/pages/mypage/like/LikeTotalFoler.tsx
  src/components/pages/mypage/shippingList/ManageShippingList.tsx
  src/components/pages/productList/BestProductNavigation.tsx
  src/components/pages/productList/EventProductList.tsx
  src/components/pages/productList/SpecialPriceNavigation.tsx
  src/components/pages/products/detail/ProductDetailInfo.tsx
  src/components/pages/products/purchase/BottomPurchaseMain.tsx
  tailwind.config.ts
Labels: 🌗Frontend, 💫 feat, ✅ test, 🎨 UI

#57 Feature/my page
  src/actions/review.tsx
  src/actions/useRevalidateTag.tsx
  src/app/(member)/mypage/review/[...slug]/page.tsx
  src/app/(member)/mypage/shippingForm/page.tsx
  src/app/(member)/mypage/shippingList/page.tsx
  src/app/api/shippingAddress/route.tsx
  src/components/pages/cart/CartShippingInfo.tsx
  src/components/pages/mypage/MyReviewSummary.tsx
  src/components/pages/mypage/review/ReviewEditor.tsx
  src/components/pages/mypage/review/WritableReviewSummary.tsx
  src/components/pages/mypage/shippingList/ManageShippingList.tsx
  src/components/pages/mypage/shippingList/ShippingForm.tsx
  src/components/pages/mypage/shippingList/ShippingInfoBox.tsx
  src/types/reviewType.tsx
Labels: 🌗Frontend, ⚙️ chore, 💫 feat, 🎨 UI

#71 Issue/69
  src/components/pages/login/SocialSignIn.tsx
Labels: 🐛 bug, 🌗Frontend, ⚙️ chore

#72 Build: test build ver.2.3
  src/components/pages/login/SocialSignIn.tsx
Labels: 🐛 bug, 🌗Frontend, ⚙️ chore

#77 Refactor: modify cartData component
  src/components/pages/mypage/CartData.tsx
Labels: 🐛 bug, 🌗Frontend

#80 Build: test build ver.2.7
  src/components/pages/products/detail/ReviewReference.tsx
  src/components/pages/products/review/PhotoReviewList.tsx
  src/components/pages/products/review/PhotoReviewPreview.tsx
  src/components/pages/products/review/RatingAndStar.tsx
  src/components/pages/products/review/ReviewSummaryList.tsx
Labels: 🐛 bug, 🌗Frontend

#82 Issue/69
  src/app/(auth)/login/social/loading.tsx
  src/app/(auth)/login/social/page.tsx
  src/app/(member)/mypage/review/[...slug]/page.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/components/pages/login/LoadMypage.tsx
  src/components/pages/login/SocialSignIn.tsx
  src/components/pages/mypage/CartData.tsx
  src/components/pages/mypage/MyReviewSummary.tsx
  src/components/pages/mypage/review/MyReviewItem.tsx
  src/components/pages/mypage/review/MyReviewList.tsx
  src/components/pages/mypage/review/ReviewEditor.tsx
  src/components/pages/mypage/review/ReviewProductInfo.tsx
  src/components/pages/mypage/review/WritableReviewSummary.tsx
  src/components/pages/products/detail/ProductDetailInfo.tsx
  src/components/pages/products/purchase/BottomPurchaseSwitcher.tsx
  src/components/pages/products/review/PhotoReviewList.tsx
  src/components/pages/products/review/PhotoReviewPreview.tsx
  src/components/pages/products/review/ProductReviewAllModal.tsx
  src/components/pages/products/review/ReviewCard.tsx
  src/components/pages/products/review/ReviewPreviewCard.tsx
  src/libs/myPageData.tsx
  src/recoil/atoms/reviewState.tsx
  src/types/reviewType.tsx
Labels: 🌗Frontend, 💫 feat
